// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wrvfbwgpaxucbsxneuao.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndydmZid2dwYXh1Y2JzeG5ldWFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTQzNDUsImV4cCI6MjA2NTQ3MDM0NX0.RqGsV851fZEEzLrN7LTjo_LjSlrdj8wHrf4FYKMQC2U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);